#!/bin/bash

set -e
cd "$(dirname "$0")/.."

# Create dev venv if it doesn't exist
if [ ! -d ".venv" ]; then
    uv venv
fi

uv pip install -r requirements.txt --upgrade
uv pip install -r requirements-rpc.txt --upgrade
uv pip install -r requirements-dev.txt --upgrade
uv pip install -r requirements-rpc3.6.txt --upgrade

# Create test venv (some elisp tests expect this to exist)
uv venv ~/.virtualenvs/elpy-test-venv

cask
cask update
